#include "system/asmhead.h"
#include "system/bmp.h"
#include "system/browser.h"
#include "system/datetime.h"
#include "system/descriptor.h"
#include "system/queue.h"
#include "system/functions.h"
#include "system/graphic.h"
#include "system/int.h"
#include "system/jpeg.h"
#include "system/language.h"
#include "system/memory.h"
#include "system/multitask.h"
#include "system/sysinfo.h"
#include "system/tek.h"
#include "system/timer.h"
#include "system/utf82kt.h"
#include "driver/file.h"
#include "driver/keyboard.h"
#include "driver/mouse.h"
#include "driver/sound.h"

#define nullptr 0
